"""
Business Rules - Reglas de negocio editables
"""

# MÁRGENES
MIN_MARGIN_PERCENTAGE = 30.0
IDEAL_MARGIN_PERCENTAGE = 40.0

# SCORING
SCORE_AUTO_PUBLISH = 80
SCORE_NEEDS_APPROVAL = 50

# IMPUESTOS MÉXICO
IVA_PERCENTAGE = 16.0
ISR_PERCENTAGE = 2.5

# PAUSAR PRODUCTOS
PAUSE_NO_SALES_DAYS = 14
PAUSE_MIN_VISITS = 50
PAUSE_MIN_CTR = 0.5

# ACTIVAR ADS
ADS_MIN_SALES = 3
ADS_MIN_MARGIN = 40.0
ADS_MIN_CTR = 2.0
ADS_MIN_ROAS = 2.0

# ESCALAR PRODUCTOS
SCALE_MIN_SALES_7DAYS = 5
SCALE_MIN_CONVERSION = 3.0
SCALE_MIN_STOCK = 10

# TEST A/B
AB_TEST_DURATION_DAYS = 7
AB_TEST_MIN_VISITS = 100
AB_TEST_MIN_SALES = 5

# OPTIMIZACIÓN DE PRECIOS
PRICE_REDUCTION_PERCENTAGE = 7.0
